# Theme metadata
name = "mixed-paper"
description = "A simple theme for writers and bloggers"
license="MIT"
homepage = "https://github.com/akainth015/mixed-paper"
demo = "https://mixed-paper.akainth.me"
# The minimum version of Zola required to use the theme
min_version = "0.7.3"

[extra]

[author]
name = "Aanand Kainth"
homepage = "https://akainth.me"

[original]
author = "WayJam So"
homepage = "https://github.com/wayjam"
repo = "https://github.com/wayjam/hugo-theme-mixedpaper"
